/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.VIEW;

import br.com.login.controller.LoginController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendell
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelaCadastroSenha = new javax.swing.JPasswordField();
        txtTelaCadastroEmail = new javax.swing.JTextField();
        txtTelaCadastroNome = new javax.swing.JTextField();
        buttonContinueTelaCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelaCadastroSenha.setText("jPasswordField1");
        txtTelaCadastroSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtTelaCadastroSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 462, 320, 40));

        txtTelaCadastroEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtTelaCadastroEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 320, 40));

        txtTelaCadastroNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtTelaCadastroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 320, 40));

        buttonContinueTelaCadastrar.setContentAreaFilled(false);
        buttonContinueTelaCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonContinueTelaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinueTelaCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonContinueTelaCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CADASTRO SIMPLES 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonContinueTelaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinueTelaCadastrarActionPerformed
       
        if(txtTelaCadastroNome.getText().matches("") || txtTelaCadastroEmail.getText().matches("") || txtTelaCadastroSenha.getText().matches("") ){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        } else{
            try{
            LoginController cadastro = new LoginController();
            cadastro.cadastrarUsuario(this);
       } catch (SQLException sql){
       
       }
        
       JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado com sucesso!");
        
       this.setVisible(false);
    }    
               
        
    }//GEN-LAST:event_buttonContinueTelaCadastrarActionPerformed

    public JPasswordField getjPasswordField1Senha() {
        return txtTelaCadastroSenha;
    }

    public void setjPasswordField1Senha(JPasswordField jPasswordField1Senha) {
        this.txtTelaCadastroSenha = jPasswordField1Senha;
    }

    public JTextField getjTextEmail() {
        return txtTelaCadastroEmail;
    }

    public void setjTextEmail(JTextField jTextEmail) {
        this.txtTelaCadastroEmail = jTextEmail;
    }

    public JTextField getjTextNome() {
        return txtTelaCadastroNome;
    }

    public void setjTextNome(JTextField jTextNome) {
        this.txtTelaCadastroNome = jTextNome;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContinueTelaCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtTelaCadastroEmail;
    private javax.swing.JTextField txtTelaCadastroNome;
    private javax.swing.JPasswordField txtTelaCadastroSenha;
    // End of variables declaration//GEN-END:variables
}
